<?xml version="1.0"?>
<package format="2">
  <name>zed_costmap_nav</name>
  <version>0.0.0</version>
  <description>El paquete principal para navegacion autonoma con camara ZED</description>
  <maintainer email="mauri@todo.todo">mauri</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>zed_interfaces</build_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>zed_interfaces</exec_depend>
  <exec_depend>robot_localization</exec_depend>
</package>
